apiVersion: apps/v1
kind: Deployment
metadata:
  name: debian
spec:
  selector:
    matchLabels:
      app: debian
  template:
    metadata:
      labels:
        app: debian
    spec:
      containers:
        - name: debian
          image: debian:12.6
